### ISSUE TITLE
On first day of the month it is failing to extract Synthetics data

### ISSUE THREAD

**Issue by aridnei** [Appdynamics/config-assessment-tool#100]
Hi all,

On first day of the month, 1st November for instance, it is failing to extract Synthetics data returning "ValueError: day is out of range for month".

`
08:36:02  2022-11-01 04:35:51,263 [INFO] emirates.saas.appdynamics.com - Extracting Synthetics
08:36:02  2022-11-01 04:35:53,595 [ERROR] Traceback (most recent call last):
08:36:02    File "/config-assessment-tool/backend/core/Engine.py", line 197, in run
08:36:02      await self.process()
08:36:02    File "/config-assessment-tool/backend/core/Engine.py", line 331, in process
08:36:02      await jobStep.extract(self.controllerData)
08:36:02    File "/config-assessment-tool/backend/extractionSteps/general/Synthetics.py", line 46, in extract
08:36:02      syntheticSessionData = await AsyncioUtils.gatherWithConcurrency(*allSyntheticSessionDataFutures)
08:36:02    File "/config-assessment-tool/backend/util/asyncio_utils.py", line 28, in gatherWithConcurrency
08:36:02      return await asyncio.gather(*[semTask(task) for task in tasks])
08:36:02    File "/config-assessment-tool/backend/util/asyncio_utils.py", line 26, in semTask
08:36:02      return await task
08:36:02    File "/config-assessment-tool/backend/api/appd/AppDService.py", line 992, in getSyntheticSessionData
08:36:02      datetime.today().replace(day=(date.today() - timedelta(date.today().weekday())).day, hour=0, minute=0, second=0, microsecond=0)
08:36:02  ValueError: day is out of range for month`

<img width="565" alt="appdynamics asseessment tool" src="https://user-images.githubusercontent.com/5923998/199167845-b0c6c0ed-f114-4253-a147-9a058219b4cd.png">

**Comment by jclutz** [comment]
This is fixed in 1.5.9.1
