### ISSUE TITLE
Config Assessment tool Error

### ISSUE THREAD

**Issue by IsaacSam-S** [Appdynamics/config-assessment-tool#132]
Using the latest version of config assessment tool (https://github.com/Appdynamics/config-assessment-tool/releases/tag/v1.6), I was able to successfully run the config assessment report for one of our SaaS controllers - 'ey-test.saas.appdynamics.com'. I made use of the platform executable method.

But, using the same utility, I am not able to extract the data for our other SaaS controller 'ey-production.saas.appdynamics.com'. The job got terminated in the middle and attached herewith is the log file.

I tried with the 1.5.4 version as well and I encounter the same error. Please let me know on how I can get rid of the error and generate the report.

[config-assessment-tool-backend.log](https://github.com/Appdynamics/config-assessment-tool/files/13446494/config-assessment-tool-backend.log)

**Comment by alexafshar** [comment]
try v1.6.1. This should be fixed in that release.  https://github.com/Appdynamics/config-assessment-tool/issues/125
