### ISSUE TITLE
Dashboards are not assessed in version 1.7.0

### ISSUE THREAD

**Issue by pshamir** [Appdynamics/config-assessment-tool#151]
Hello. I successfully tested the oAuth functionality in 1.7.0 (thanks!), but when comparing the results to previous versions I noticed a big gap.
I didn't review all the threshold sections yet, but the first thing that jumped out was the dashboards. The new version is showing them all as 0 which is not in line with previous versions. Can this be looked into please?

**Comment by alexafshar** [comment]
Hi, customer controller version should be 24.7 and above.  Dashboard API's didn't properly support oAuth tokens for some of the versions prior to that.

**Comment by alexafshar** [comment]
closing this out as dashboard API's now support tokens on newer controller version 24.7.
