### ISSUE TITLE
Allow API Client Auth

### ISSUE THREAD

**Issue by bhjelmar** [Appdynamics/config-assessment-tool#92]
https://docs.appdynamics.com/appd/21.x/21.3/en/extend-appdynamics/appdynamics-apis/api-clients

**Comment by pshamir** [comment]
Hello, is this enhancement planned to be progressed in the near future? 
If not, is there a way to use the tool on SaaS controllers that can only be accessed through SAML or API Clients?

**Comment by alexafshar** [comment]
This one is on-hold as some API's we use don't support oAuth yet.  IDEA submitted to be addressed by the team.  No ETA yet. IDEA-5868. Note this is not accessible external to AppD.

**Comment by alexafshar** [comment]
support for this is now in v1.7.0+ release.
